/**
 * 食材静态预设数据，与 Flutter 版 lib/data/default_items.dart 保持一致。
 * 图片资源位于 /assets/images/，命名规范：<id>_<name>.png
 */

// 左侧分类参考火锅点单常见结构：肉类拆牛羊，蔬菜/菌菇独立，
// 丸滑豆制和主食保留为高频涮锅分组。
const CATEGORIES = [
  '全部',
  '已点',
  '推荐',
  '牛肉',
  '羊肉',
  '内脏',
  '丸滑豆制',
  '海鲜',
  '青菜',
  '菌菇',
  '主食',
];

const DEFAULT_ITEMS = [
  {
    id: '1',
    name: '脆爽毛肚',
    category: '内脏',
    targetSeconds: 15,
    aliases: ['毛肚', '牛百叶', '百叶', 'maodu'],
    emoji: '🥩',
    imagePath: '/assets/images/1_maodu.png',
  },
  {
    id: '2',
    name: '鲜切鸭肠',
    category: '内脏',
    targetSeconds: 12,
    aliases: ['鸭肠', '鹅肠', 'duchang'],
    emoji: '🐤',
    imagePath: '/assets/images/2_duchang.png',
  },
  {
    id: '3',
    name: '嫩牛肉',
    category: '牛肉',
    targetSeconds: 30,
    aliases: ['牛肉', '嫩牛', '鲜牛肉', 'niuniu', 'niurou'],
    emoji: '🥓',
    imagePath: '/assets/images/3_niuniu.png',
  },
  {
    id: '4',
    name: '潮汕牛肉丸',
    category: '丸滑豆制',
    targetSeconds: 600,
    aliases: ['牛肉丸', '肉丸', '丸子', 'niuwan'],
    emoji: '🧆',
    imagePath: '/assets/images/4_niuwan.png',
  },
  {
    id: '5',
    name: '虾滑',
    category: '丸滑豆制',
    targetSeconds: 240,
    aliases: ['虾滑', '虾丸', 'xiahua'],
    emoji: '🦐',
    imagePath: '/assets/images/5_xiahua.png',
  },
  {
    id: '6',
    name: '嫩豆腐',
    category: '丸滑豆制',
    targetSeconds: 180,
    aliases: ['豆腐', '嫩豆腐', '冻豆腐', 'doufu'],
    emoji: '🧈',
    imagePath: '/assets/images/6_doufu.png',
  },
  {
    id: '7',
    name: '金针菇',
    category: '菌菇',
    targetSeconds: 90,
    aliases: ['金针菇', '菌菇', '蘑菇', 'jinzhengu'],
    emoji: '🍄',
    imagePath: '/assets/images/7_jinzhengu.png',
  },
  {
    id: '8',
    name: '宽粉',
    category: '主食',
    targetSeconds: 300,
    aliases: ['宽粉', '粉条', '红薯粉', 'kuanfen'],
    emoji: '🍜',
    imagePath: '/assets/images/8_kuanfen.png',
  },
  {
    id: '9',
    name: '鹌鹑蛋',
    category: '丸滑豆制',
    targetSeconds: 360,
    aliases: ['鹌鹑蛋', '鸟蛋', 'anchundun', 'anchundan'],
    emoji: '🥚',
    imagePath: '/assets/images/9_anchundun.png',
  },
  {
    id: '10',
    name: '生菜',
    category: '青菜',
    targetSeconds: 20,
    aliases: ['生菜', '青菜', '蔬菜', 'shengcai'],
    emoji: '🥬',
    imagePath: '/assets/images/10_shengcai.png',
  },
  {
    id: '11',
    name: '肥牛卷',
    category: '牛肉',
    targetSeconds: 25,
    aliases: ['肥牛', '肥牛卷', '牛肉卷', 'fatty beef'],
    emoji: '🥩',
    imagePath: '/assets/images/11_feiniu.png',
  },
  {
    id: '12',
    name: '牛舌',
    category: '牛肉',
    targetSeconds: 45,
    aliases: ['牛舌', 'beef tongue'],
    emoji: '🥩',
    imagePath: '/assets/images/12_niushe.png',
  },
  {
    id: '13',
    name: '羊肉卷',
    category: '羊肉',
    targetSeconds: 30,
    aliases: ['羊肉', '羊肉卷', '羔羊', 'lamb'],
    emoji: '🥩',
    imagePath: '/assets/images/13_yangrou.png',
  },
  {
    id: '14',
    name: '黄喉',
    category: '内脏',
    targetSeconds: 45,
    aliases: ['黄喉', 'huanghou'],
    emoji: '🥢',
    imagePath: '/assets/images/14_huanghou.png',
  },
  {
    id: '15',
    name: '鱼片',
    category: '海鲜',
    targetSeconds: 60,
    aliases: ['鱼片', '黑鱼片', '鱼', 'fish'],
    emoji: '🐟',
    imagePath: '/assets/images/15_yupian.png',
  },
  {
    id: '16',
    name: '鲜虾',
    category: '海鲜',
    targetSeconds: 180,
    aliases: ['虾', '鲜虾', '基围虾', 'shrimp'],
    emoji: '🦐',
    imagePath: '/assets/images/16_xianxia.png',
  },
  {
    id: '17',
    name: '油麦菜',
    category: '青菜',
    targetSeconds: 25,
    aliases: ['油麦菜', '莴苣叶'],
    emoji: '🥬',
    imagePath: '/assets/images/17_youmaicai.png',
  },
  {
    id: '18',
    name: '娃娃菜',
    category: '青菜',
    targetSeconds: 60,
    aliases: ['娃娃菜', '白菜'],
    emoji: '🥬',
    imagePath: '/assets/images/18_wawacai.png',
  },
  {
    id: '19',
    name: '香菇',
    category: '菌菇',
    targetSeconds: 180,
    aliases: ['香菇', '蘑菇', 'shiitake'],
    emoji: '🍄',
    imagePath: '/assets/images/19_xianggu.png',
  },
  {
    id: '20',
    name: '土豆片',
    category: '主食',
    targetSeconds: 240,
    aliases: ['土豆', '土豆片', '马铃薯'],
    emoji: '🥔',
    imagePath: '/assets/images/20_tudoupian.png',
  },
];

module.exports = { CATEGORIES, DEFAULT_ITEMS };
